### ISSUE TITLE
What different between AHT v2.9.4.ahk and AHT.v2.9.4.exe ???

### ISSUE THREAD

**Issue by khongthequenbluestar** [AucT/AucT-Hotkeys-Tool#2]
Hello,
I used AHT.v2.9.4.exe which was compiled from https://aht.auct.eu/download.html, It work perfect
But when i run script AHT v2.9.4.ahk, it freeze my screen when i press multi key at the same time.
=> What different between AHT v2.9.4.ahk and AHT.v2.9.4.exe ???

I compiled AHT v2.9.4.ahk -> .exe file, it has 1,158 Kb, but AHT.v2.9.4.exe which i download from website it only 250 Kb
=> Why??? Maybe it is cause to make my screen freeze

Could you guide to me to re-build (re-compile) .AHK -> .exe ???

Thanks,

**Comment by AucT** [comment]
you need to compile it with old (classic) autohotkey
https://autohotkey.com/board/topic/86134-autohotkey-10-classic-and-basic-versions/

**Comment by khongthequenbluestar** [comment]
@AucT 
Now it work very perfect
Yes, thank you very much,

**Comment by anhduc1985** [comment]
Fixed
