### ISSUE TITLE
can u update to 1.30PTR?

### ISSUE THREAD

**Issue by hegelsu** [AucT/AucT-Hotkeys-Tool#5]
can u update to 1.30PTR?
https://us.battle.net/forums/en/bnet/topic/20765647087

**Comment by AucT** [comment]
No
Can't find memory address with module. They somehow changed the way it was before.

Use it without chat-suspend feature (to turn off go to Chat-Suspend->uncheck chat-free in game) and manually turn on off with hotkey or use another hotkey tool. At least for now.

I'll try more but I don't think I can solve this.

**Comment by hegelsu** [comment]
thanks

**Comment by ghost** [comment]
@auct Could you retry please? Patch 1.30 was released.

**Comment by hegelsu** [comment]
@Myll this is my keytools: https://github.com/hegelsu/SuWar3Tools
support check chat-free in 1.30(not to find memory)

**Comment by AucT** [comment]
Released v2.9.9 https://github.com/AucT/AucT-Hotkeys-Tool/releases/tag/v2.9.9

Not tested much though.

**Comment by hegelsu** [comment]
@AucT my tools used color detecting also in 1.30. I check yellow color in chat message input area.

**Comment by AucT** [comment]
@hegelsu make english version so I can forget about wc3 already)

**Comment by hegelsu** [comment]
@AucT updated! but I'm not good at English.
