### ISSUE TITLE
re-enable application when use skill

### ISSUE THREAD

**Issue by khongthequenbluestar** [AucT/AucT-Hotkeys-Tool#6]
Dear develop team

I am using this hotkey in DoTA1.
Before i was using AHT v2.9.8, it dont happend
In new version AHT v2.9.10, when i use skill some time application re-enable.
EX:  when skill is activating, the cursor is moving on screen, at this time the hotkey re-enable so activity be interrupt, sometime make screen moving by when i clicking skill and app re-enable so the position of cursor be change.

Currently i custom your code and add sound file when enable/disable hotkey so i can hear them when app re-enable.
I think: root cause is:
The timer check screen of warcraft in/out game (in lobby or in game). some time it re-active hotkey.

It inconvenience, I hope you will fix this bug

Thanks and regards,

**Comment by AucT** [comment]
for wc3 that is 1.29 or less use v2.9.8

The new hotkey versions are not reading memory. 2.9.10 listens to enter click for chat disabling/enabling

I don't understand your description. Try in simple words without re-enable. Is it about double clicking same custom skill hotkey?

**Comment by khongthequenbluestar** [comment]
Current game info:
Ranked Gaming Client
Warcraft III: 1.26.0.6401

**"re-enable"**: it mean maybe the code:
   **Suspend on
   Suspend off
OR
   reload**
In app, i checked selftcast on double-click
I dont know why the bug happened

i used:
AHT v2.9.10: chat system work well
AHT v2.9.8: chat system don't work
so i don't want to use AHT v2.9.8

With my game info: what hotkey version should i use?

In app: if i check **New Warcraft UI (1.29+)**, does it mean? it work like previous version hotkey?

**Comment by AucT** [comment]
use v2.9.4

**Comment by khongthequenbluestar** [comment]
I will try, and feedback later
Thanks

**Comment by khongthequenbluestar** [comment]
Thank you very much,
v2.9.4 work well with current my game info, chat system also work well,
