### ISSUE TITLE
How to remap ctrl and space alone?

### ISSUE THREAD

**Issue by luboq** [AucT/AucT-Hotkeys-Tool#7]
For a long time I've been using a simple script I wrote. However, its disadvantage is suspend during chat is not working very smoothly.

To solve this once and for all, I want to move my whole current scheme, which quoted below, to AucT-Hotkeys-Tool, which I just found recently and happily, but I don't know how to remap some special keys alone. Can you help me? Thanks.

```
    ~MButton & s::Suspend
    RControl & RShift::AltTab  ; 按住右 control 后接着反复下右 shift 来向前移动.

    ; 编队
    LAlt::RControl              ;alt改成ctrl
    Space::Shift                ;space改成shift
    s::1
    d::2
    f::3
    g::4
    a::5
    NumpadMult::6
    
    ; 英雄
    x::F1
    c::F2
    b::F3
    
    ; 技能键 物品栏
    LShift::i                   ;shift改成i
    1::k
    2::y
    3::h
    4::m
    F1::Numpad7
    F2::Numpad8
    F3::Numpad4
    F4::Numpad5                
    
    ; 杂项
    LWin::Space
    `::F8                       ;闲置农民
    LCtrl::BackSpace            ;基地
    Esc::Esc
```

**Comment by luboq** [comment]
I tried to write like this in `setting.ini`, it's not working

```
[RemapKey]
KRhotkey1=LAlt    
KRvalue1=RControl   
KRhotkey2=Space 
KRvalue2=Shift 
```

**Comment by hegelsu** [comment]
你QQ多少，交流下？

**Comment by luboq** [comment]
1755三81九95
不过我是小白哈，不懂程序
你的工具我也在用，单机时用来调视距

这个聊天框下禁用脚本，快把我搞疯了，用回车检测也不靠谱，因为输入法里可能用到回车

hegelsu <notifications@github.com> 于2018年10月17日周三 下午2:36写道：

**Comment by AucT** [comment]
insert your code in aht, just before
```


;==================================================================================  
;=====================================GUI==========================================
;==================================================================================  


```

So it should look like

```
	
    LAlt::RControl
    Space::Shift
	
;==================================================================================  
;=====================================GUI==========================================
;==================================================================================  

```


Note if you are using wc3 1.30  - use aht v2.9.11 (latest)
If your patch is 1.29 or less - use aht v2.9.8
You can download source code from releases or https://aht.auct.eu/download.html

Edit file with .ahk extenstion as I mentioned above and compile with old classic autohokey

I will try make it work from gui, but not very soon
